### PR TITLE
Added a co-prime function

### PR DESCRIPTION
**Pull request by SohamGhugare**

### CODE REVIEW

**Comment by Seniatical** [comment]
Looks good!

**Comment by Seniatical** [comment]
Since the function is a check could you possibly rename it to something like `is_coprime` or `is_co_prime`?

**Comment by SohamGhugare** [comment]
`is_coprime` sounds good, will do it soon

**Comment by Seniatical** [comment]
👍

**Comment by Seniatical** [comment]
Nice

**Pull request merged**
